### ISSUE TITLE
HumanPolicy

### ISSUE THREAD

**Issue by eyuansu62** [princeton-nlp/intercode#1]
In the run_sql.py, you initialize the pocily by policy = HumanPolicy().
Shouldn't it be ChatGPTPolicy?

**Comment by john-b-yang** [comment]
Hello! Thanks for your comment.

The `run_<code>.py` files are more meant to be demonstrations that allow you to directly interact with InterCode environments.

It is not intended to showcase how to run language models end to end on these environments. If you're looking for examples, please check out the [experiments](https://github.com/princeton-nlp/intercode/tree/master/experiments) folder and the [wiki](https://github.com/princeton-nlp/intercode/wiki/4.-Experiments-%F0%9F%A7%AA) for a more high level overview.

Hope this helps! If you have any additional comments, feel free to follow up. Otherwise, I'll close this in a day.
